name: CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-node@v6
        with:
          node-version-file: ".nvmrc"
      - name: Set up corepack
        run: |
          corepack enable && corepack install
          yarn --version
      - name: Install dependencies
        run: yarn install --immutable
      - name: Build
        run: yarn run build
    #   - name: Create Release
    #     if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    #     run: |
    #       git config --global user.name "GitHub Actions"
    #       git config --global user.email "actions@github.com"
    #       yarn changeset version
    #       git add .
    #       git commit -m "chore: version packages"
    #       git push
    #       yarn changeset publish
